CREATE TABLE IF NOT EXISTS projects(
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
name VARCHAR NOT NULL,
is_archive BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
